apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kiali-bookinfo
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kiali-bookinfo
subjects:
- kind: Group
  name: oidc:default
  namespace: bookinfo
