apiVersion: v1
kind: Secret
metadata:
  name: grafana-bearer-token
  namespace: istio-system
type: Opaque
stringData:
  TOKEN: mi-token-secreto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-nginx-config
  namespace: istio-system
data:
  default.conf.template: |
    server {
      listen 3000 ssl;

      ssl_certificate     /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;

      location / {
        if ($http_authorization != "Bearer $TOKEN") {
          return 401;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://grafana.istio-system:3000;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-proxy
  template:
    metadata:
      labels:
        app: grafana-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 3000
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-bearer-token
                  key: TOKEN
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: tls
              mountPath: /etc/nginx/tls
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: grafana-nginx-config
        - name: tls
          secret:
            secretName: grafana-proxy-tls

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  namespace: istio-system
spec:
  selector:
    app: grafana-proxy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

